default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: twenty200817_falconyDemo_001_development

test:
  <<: *default
  database: twenty200817_falconyDemo_001_development
